
package com.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarServiceService", targetNamespace = "http://app.com/", wsdlLocation = "http://127.0.0.1:8085/car?wsdl")
public class CarServiceService
    extends Service
{

    private final static URL CARSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CARSERVICESERVICE_EXCEPTION;
    private final static QName CARSERVICESERVICE_QNAME = new QName("http://app.com/", "CarServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8085/car?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARSERVICESERVICE_WSDL_LOCATION = url;
        CARSERVICESERVICE_EXCEPTION = e;
    }

    public CarServiceService() {
        super(__getWsdlLocation(), CARSERVICESERVICE_QNAME);
    }

    public CarServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARSERVICESERVICE_QNAME, features);
    }

    public CarServiceService(URL wsdlLocation) {
        super(wsdlLocation, CARSERVICESERVICE_QNAME);
    }

    public CarServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARSERVICESERVICE_QNAME, features);
    }

    public CarServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarService
     */
    @WebEndpoint(name = "CarServicePort")
    public CarService getCarServicePort() {
        return super.getPort(new QName("http://app.com/", "CarServicePort"), CarService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarService
     */
    @WebEndpoint(name = "CarServicePort")
    public CarService getCarServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app.com/", "CarServicePort"), CarService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARSERVICESERVICE_EXCEPTION!= null) {
            throw CARSERVICESERVICE_EXCEPTION;
        }
        return CARSERVICESERVICE_WSDL_LOCATION;
    }

}
