
package com.app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyCalculator", targetNamespace = "http://app.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyCalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://app.com/", className = "com.app.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://app.com/", className = "com.app.AddResponse")
    @Action(input = "http://app.com/MyCalculator/addRequest", output = "http://app.com/MyCalculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://app.com/", className = "com.app.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://app.com/", className = "com.app.DivideResponse")
    @Action(input = "http://app.com/MyCalculator/divideRequest", output = "http://app.com/MyCalculator/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "product", targetNamespace = "http://app.com/", className = "com.app.Product")
    @ResponseWrapper(localName = "productResponse", targetNamespace = "http://app.com/", className = "com.app.ProductResponse")
    @Action(input = "http://app.com/MyCalculator/productRequest", output = "http://app.com/MyCalculator/productResponse")
    public int product(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://app.com/", className = "com.app.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://app.com/", className = "com.app.SubtractResponse")
    @Action(input = "http://app.com/MyCalculator/subtractRequest", output = "http://app.com/MyCalculator/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
